name: Bug report
description: Report an issue or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please include enough detail to reproduce the issue.
  - type: input
    id: version
    attributes:
      label: SEO Audit Agent version
      placeholder: "0.3.0"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11"
    validations:
      required: true
  - type: textarea
    id: command
    attributes:
      label: Command run
      placeholder: "seo-agent https://example.com --goal 'traffic growth'"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Include relevant output or error messages.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, logs, or screenshots.
    validations:
      required: false
