name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Share the problem you are trying to solve and what success looks like.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What is the pain point or missing capability?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred approach or workflow.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternatives you have tried.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, or example output.
    validations:
      required: false
